In [2]:
from functions.load_data import *
from functions.plotting import animate_stick
import pyvista as pv
pv.set_jupyter_backend('trame')

In [3]:
    ds_all, ds_all_centered, datasets, datasets_centered, ds_counts = load_data(pattern="../data/mariel_*.npy")
    seq_len = 10
    index_start = 0
    # index_start = np.random.randint(0,len(ds_all_centered)-seq_len)
    print("Seeding with frame {}".format(index_start))
    xtest = ds_all_centered[index_start:index_start + seq_len, :, :3]
    print(xtest)

    animate_stick(xtest, figsize=(10, 8), cmap='inferno', cloud=False)

Original numpy dataset contains 38,309 timesteps of 53 joints with 3 dimensions each.
loc_min: -1.8967371874141707 loc_max: 1.5558704656286815
vel_min: -45.57506836403084 vel_max: 33.951220235113276
loc_min: -0.4843721412027978 loc_max: 0.9283637015363149
vel_min: -45.57506836403084 vel_max: 33.951220235113276
Seeding with frame 0
[[[-0.38773259 -0.0288093   0.03612741]
  [-0.33834185 -0.18721885  0.04133357]
  [-0.31978013 -0.19094758 -0.07204046]
  ...
  [-0.4574029  -0.24783214 -0.07250286]
  [-0.27387647 -0.3043228  -0.09858788]
  [-0.30346665 -0.28685643  0.04165096]]

 [[-0.3969449  -0.03415808  0.0376016 ]
  [-0.33925403 -0.19041847  0.03968402]
  [-0.32060699 -0.19089635 -0.0729241 ]
  ...
  [-0.45667333 -0.25296909 -0.07553994]
  [-0.2660152  -0.30013029 -0.10094972]
  [-0.29820253 -0.28743478  0.0387202 ]]

 [[-0.40685949 -0.03911497  0.03939015]
  [-0.34114064 -0.19338324  0.03809435]
  [-0.32258524 -0.19060577 -0.07366156]
  ...
  [-0.45574316 -0.25765079 -0.07934889]
  [-0

Widget(value='<iframe src="http://localhost:56949/index.html?ui=P_0x2119f745550_0&reconnect=auto" class="pyvis…